name: main_workflow

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup project
              run: |
                make setup &&
                make start
            - name: Run test
              run: make test
            - name: Run linter
              run: make lint
