name: main_workflow

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
              uses: actions/checkout@v4
              run: make setup
              run: make start
              run: make test
              run: make lint
